In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
file="Resources/holiday_songs.csv"
df = pd.read_csv(file)
df.head()

,Unnamed: 0,track_uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,tempo,duration_ms,time_signature,key_mode,playlist_name,playlist_img,track_name,artist_name,album_name,album_img
0,1,00IqwkT0PZhJ86PJajRCqk,0.195,0.348,A#,-10.106,major,0.0332,0.820000,0.000000,...,166.824,213107,3,A# major,new_holiday_songs,https://mosaic.scdn.co/640/5f79f928a45b878579e...,Silver Bells,Johnny Mathis,Merry Christmas,https://i.scdn.co/image/b878b9e27201163be07e74...
1,2,01h424WG38dgY34vkI3Yd0,0.225,0.248,A,-15.871,major,0.0337,0.912000,0.000143,...,96.013,183613,4,A major,new_holiday_songs,https://mosaic.scdn.co/640/5f79f928a45b878579e...,White Christmas,Bing Crosby,White Christmas,https://i.scdn.co/image/3bb0daf5f87a737ce67ace...
2,3,08BhfyKUXxZrnyHrDavNHP,0.444,0.288,F#,-11.793,major,0.0326,0.911000,0.000007,...,108.043,199093,3,F# major,new_holiday_songs,https://mosaic.scdn.co/640/5f79f928a45b878579e...,The Christmas Waltz,Tony Bennett,A Swingin' Christmas Featuring The Count Basie...,https://i.scdn.co/image/96aa4fb09e7fe9d38599c8...
3,4,095XSaT8I2uI6Uldj2QrSl,0.687,0.496,A,-4.708,major,0.0339,0.434000,0.001440,...,97.575,178680,4,A major,new_holiday_songs,https://mosaic.scdn.co/640/5f79f928a45b878579e...,Stop the Cavalry,Jona Lewie,On The Other Hand There's A Fist (Remastered),https://i.scdn.co/image/50c0ea35cacbf7c5d495c7...
4,5,09b2gJR45Pyip2rx9CnXW1,0.477,0.841,F#,-5.172,major,0.0358,0.000165,0.097100,...,119.954,203404,4,F# major,new_holiday_songs,https://mosaic.scdn.co/640/5f79f928a45b878579e...,I Don't Want to Go Home for Christmas,Independent Counsel of Funk,I Don't Want to Go Home for Christmas,https://i.scdn.co/image/77eb7c17cafe55037a1ab2...

In [3]:
holiday_df=df[["track_name","artist_name","danceability"]].copy()
holiday_df

,track_name,artist_name,danceability
0,Silver Bells,Johnny Mathis,0.195
1,White Christmas,Bing Crosby,0.225
2,The Christmas Waltz,Tony Bennett,0.444
3,Stop the Cavalry,Jona Lewie,0.687
4,I Don't Want to Go Home for Christmas,Independent Counsel of Funk,0.477
...,...,...,...
162,Run Run Rudolph,Kelly Clarkson,0.572
163,Christmas in Our Hearts,Jose Mari Chan,0.570
164,I Want a Hippopotamus for Christmas (Hippo the...,Gayla Peevey,0.838
165,When a Child Is Born,Johnny Mathis,0.350
166,Feliz Navidad,JosÃ© Feliciano,0.496

In [4]:
holiday_df.columns = ("Song_Name", "Artist", "Danceability")
holiday_df.head()

,Song_Name,Artist,Danceability
0,Silver Bells,Johnny Mathis,0.195
1,White Christmas,Bing Crosby,0.225
2,The Christmas Waltz,Tony Bennett,0.444
3,Stop the Cavalry,Jona Lewie,0.687
4,I Don't Want to Go Home for Christmas,Independent Counsel of Funk,0.477

In [7]:
holiday_df.nunique()

Song_Name       135
Artist          121
Danceability    144
dtype: int64

In [8]:
csv_file = "./Resources/featuresdf.csv"
music_df = pd.read_csv(csv_file)
music_df.head()

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.5810,0.000000,0.0931,0.931,95.977,233713.0,4.0
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.2290,0.000000,0.0924,0.813,88.931,228827.0,4.0
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.2090,0.000000,0.1120,0.846,177.833,228200.0,4.0
3,6RUKPb4LETWmmr3iAEQkt,Something Just Like This,The Chainsmokers,0.617,0.635,11.0,-6.769,0.0,0.0317,0.0498,0.000014,0.1640,0.446,103.019,247160.0,4.0
4,3DXncPQOG4VBw3QHh3S81,I'm the One,DJ Khaled,0.609,0.668,7.0,-4.284,1.0,0.0367,0.0552,0.000000,0.1670,0.811,80.924,288600.0,4.0

In [9]:
new_music_df = music_df[['name', 'artists', 'danceability']].copy()
new_music_df.head()

                                 name           artists  danceability
0                        Shape of You        Ed Sheeran         0.825
1                   Despacito - Remix        Luis Fonsi         0.694
2  Despacito (Featuring Daddy Yankee)        Luis Fonsi         0.660
3            Something Just Like This  The Chainsmokers         0.617
4                         I'm the One         DJ Khaled         0.609

In [10]:
new_music_df.columns = ("Song Name", "Artist", "Danceability")
new_music_df.head()

                            Song Name            Artist  Danceability
0                        Shape of You        Ed Sheeran         0.825
1                   Despacito - Remix        Luis Fonsi         0.694
2  Despacito (Featuring Daddy Yankee)        Luis Fonsi         0.660
3            Something Just Like This  The Chainsmokers         0.617
4                         I'm the One         DJ Khaled         0.609

In [11]:
new_music_df.nunique()

Song Name       100
Artist           78
Danceability     93
dtype: int64

In [20]:
#Connection to local db

rds_connection_string = "postgres:postgres@localhost:5432/Holiday Music"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [21]:
#Check for tables
engine.table_names()

['Holiday_Music', '2017_Music']

In [14]:
holiday_df.to_sql(name='2017_Music', con=engine, if_exists='append', index=False)

In [25]:
pd.read_sql_query('select * from "2017_Music"', con=engine)

,Song_Name,Artist,Danceability
0,Silver Bells,Johnny Mathis,0
1,White Christmas,Bing Crosby,0
2,The Christmas Waltz,Tony Bennett,0
3,Stop the Cavalry,Jona Lewie,1
4,I Don't Want to Go Home for Christmas,Independent Counsel of Funk,0
...,...,...,...
329,Run Run Rudolph,Kelly Clarkson,1
330,Christmas in Our Hearts,Jose Mari Chan,1
331,I Want a Hippopotamus for Christmas (Hippo the...,Gayla Peevey,1
332,When a Child Is Born,Johnny Mathis,0
333,Feliz Navidad,JosÃ© Feliciano,0

In [26]:
holiday_df.to_sql(name='Holiday_Music', con=engine, if_exists='append', index=False)

In [27]:
pd.read_sql_query('select * from "Holiday_Music"', con=engine).head()

,Song_Name,Artist,Danceability
0,Silver Bells,Johnny Mathis,0
1,White Christmas,Bing Crosby,0
2,The Christmas Waltz,Tony Bennett,0
3,Stop the Cavalry,Jona Lewie,1
4,I Don't Want to Go Home for Christmas,Independent Counsel of Funk,0